events {}
http {
  server {
    listen 8080;

    add_header Access-Control-Allow-Origin "http://127.0.0.1:25128" always;
    add_header Access-Control-Allow-Headers "Authorization,Content-Type,X-Biz-Code,X-Partner-Code" always;
    add_header Access-Control-Allow-Methods "GET,POST,PATCH,PUT,DELETE,OPTIONS" always;

    if ($request_method = OPTIONS) { return 204; }

    location /api/v1/auth/ {
      proxy_pass http://sol1229r5-partner-auth:8091/api/v1/auth/;
      proxy_set_header Host $host;
    }
    location /api/v1/partner-orders/ {
      proxy_pass http://sol1229r5-partner-order:8088/api/v1/partner-orders/;
      proxy_set_header Host $host;
    }
    location /api/v1/products {
      proxy_pass http://sol1229r5-product:8084/api/v1/products;
      proxy_set_header Host $host;
    }
    location /api/version {
      proxy_pass http://host.docker.internal:8080/api/version;
      proxy_set_header Host $host;
    }
  }
}
