plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports { mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES }
}

dependencies {
    api project(':shared:audit-contract')
    api 'org.springframework.boot:spring-boot-autoconfigure'
    api 'org.springframework.boot:spring-boot-starter-amqp'
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework:spring-tx'
    api 'io.micrometer:micrometer-core'
    api 'org.slf4j:slf4j-api'
    compileOnly 'org.projectlombok:lombok:' + lombokVersion
    annotationProcessor 'org.projectlombok:lombok:' + lombokVersion
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:rabbitmq:1.20.3'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') { useJUnitPlatform() }
