import { describe, expect, it } from 'vitest'
import { toHometaxResultRow, type HometaxPreviewRow } from './hometaxExportApi'

describe('홈택스 결과표 wire DTO 투영', () => {
  it('백엔드 HomtaxRow의 전 열을 결과표가 같은 값으로 표시한다', () => {
    const wireRow: HometaxPreviewRow = {
      invoiceType: '01',
      writeDate: '20260810',
      supplierRegNo: '1234567890',
      supplierSubNo: '',
      supplierName: '공급자',
      supplierCeo: '공급자대표',
      supplierAddress: '공급자주소',
      supplierBizType: '도소매',
      supplierBizItem: '에어컨',
      supplierEmail: 'supplier@example.com',
      buyerRegNo: '1130710031',
      buyerSubNo: '',
      buyerName: '공급받는자',
      buyerCeo: '받는자대표',
      buyerAddress: '받는자주소',
      buyerBizType: '도소매',
      buyerBizItem: '설비',
      buyerEmail1: 'buyer@example.com',
      buyerEmail2: '',
      supplyAmount: '909',
      vatAmount: '90',
      remark: '배송주소',
      itemDate1: '10',
      itemName1: '실외기',
      itemSpec1: '규격A',
      itemQty1: '1',
      itemPrice1: '909',
      itemSupply1: '909',
      itemVat1: '90',
      itemRemark1: '품목비고',
      itemDate2: '', itemName2: '', itemSpec2: '', itemQty2: null, itemPrice2: null,
      itemSupply2: null, itemVat2: null, itemRemark2: '',
      itemDate3: '', itemName3: '', itemSpec3: '', itemQty3: null, itemPrice3: null,
      itemSupply3: null, itemVat3: null, itemRemark3: '',
      itemDate4: '', itemName4: '', itemSpec4: '', itemQty4: null, itemPrice4: null,
      itemSupply4: null, itemVat4: null, itemRemark4: '',
      cash: null, check: null, bill: null, credit: null,
      receiptType: '02',
      slipNo: '2026/08/10-25',
      partnerCode: 'P-2026-0001',
    }

    expect(toHometaxResultRow(wireRow, 1)).toMatchObject({
      rowNo: 1,
      slipNo: '2026/08/10-25',
      writeDate: '20260810',
      supplierName: '공급자',
      supplierRegNo: '1234567890',
      buyerName: '공급받는자',
      buyerRegNo: '1130710031',
      buyerEmail1: 'buyer@example.com',
      supplyAmount: '909',
      vatAmount: '90',
      totalAmount: '999',
      itemName1: '실외기',
      itemSpec1: '규격A',
      itemQty1: '1',
      itemPrice1: '909',
      partnerCode: 'P-2026-0001',
      remark: '배송주소',
    })
  })
})
