package com.samhanair.logis.auth.menu;

import java.util.List;

/** 본체와 아로로지스 데스크톱이 공유하는 공식 메뉴 정본. */
public final class MenuCatalog {

    private static final List<MenuCatalogEntry> ENTRIES = List.of(
            entry("samhan-public", "판매", "판매관리", "/sales", "sales.slip.list", 1),
            entry("samhan-public", "판매", "견적서 관리", "/sales/estimates", "estimates.list", 2),
            entry("samhan-public", "판매", "주문서 관리", "/sales/partner-orders", "sales.partner-order.list", 3),
            entry("samhan-public", "판매", "주문서 승인", "/sales/order-approvals", "sales.partner-order.list", 4),
            entry("samhan-public", "판매", "거래처 관리", "/admin/partners", "partners.list", 5),
            entry("samhan-public", "판매", "거래처 DC 설정", "/sales/partner-dc-config", "sales.partner-dc-config", 6),
            entry("samhan-public", "판매", "발송금지 거래처", "/admin/blocked-partners", "partners.block", 7),
            entry("samhan-public", "판매", "전표 정리", "/sales/slip-cleanup", "slip.cleanup", 8),
            entry("samhan-public", "판매", "내일자 전표 이미지", "/sales/next-day-slip", "slip.print.next-day", 9),
            entry("samhan-public", "판매", "기초품목 관리", "/products/catalog", "products.list", 10),
            entry("samhan-public", "판매", "견적품목 관리", "/products/estimate-items", "products.list", 11),
            entry("samhan-public", "판매", "분류 관리", "/products/classifications", "products.list", 12),
            entry("samhan-public", "판매", "카테고리별 단가변동", "/products/price-schedule", "products.price-schedule", 13),
            entry("samhan-public", "판매", "시트 동기화", "/admin/sheet-sync", "products.sync", 14),
            entry("samhan-public", "구매", "구매관리", "/purchases", "purchases.slip.list", 1),
            entry("samhan-public", "구매", "재고이동 관리", "/transfers", "inventory.stock-transfer", 2),
            entry("samhan-public", "구매", "입고 검수", "/warehouse/inbound-inspections", "inbound.inspection", 3),
            entry("samhan-public", "구매", "재고 실사", "/warehouse/audit", "inventory.audit", 4),
            entry("samhan-public", "구매", "DPS 입고 비교", "/warehouse/dps-compare", "inventory.dps", 5),
            entry("samhan-public", "구매", "품목별 DPS 분석", "/warehouse/dps-compare/by-product", "inventory.dps", 6),
            entry("samhan-public", "회계", "매출전표", "/accounting/sales-slips", "accounting.sales-slip.accounting", 1),
            entry("samhan-public", "회계", "매입전표", "/accounting/purchase-slips", "accounting.purchase-slip.accounting", 2),
            entry("samhan-public", "회계", "계정과목", "/accounting/accounts", "accounting.accounts", 3),
            entry("samhan-public", "회계", "분개장", "/accounting/journals", "accounting.journals", 4),
            entry("samhan-public", "회계", "세금계산서", "/accounting/tax-invoices", "accounting.tax-invoice.list", 5),
            entry("samhan-public", "회계", "수신 세금계산서", "/accounting/tax-invoices/inbound", "accounting.tax-invoice.inbound.manage", 6),
            entry("samhan-public", "회계", "합계잔액시산표", "/accounting/balances", "accounting.balances", 7),
            entry("samhan-public", "회계", "재무 보고서", "/accounting/reports", "accounting.reports", 8),
            entry("samhan-public", "회계", "손익계산서", "/accounting/reports/income-statement", "accounting.reports", 9),
            entry("samhan-public", "회계", "월별손익분석", "/accounting/reports/income-statement/monthly", "accounting.reports", 10),
            entry("samhan-public", "회계", "재무상태표", "/accounting/reports/balance-sheet", "accounting.reports", 11),
            entry("samhan-public", "회계", "부가세 신고서", "/accounting/reports/vat", "accounting.reports", 12),
            entry("samhan-public", "회계", "법인세 신고서", "/accounting/reports/corporate-tax", "accounting.reports", 13),
            entry("samhan-public", "회계", "미수금 (거래처별)", "/accounting/reports/partner-aging?type=RECEIVABLE", "accounting.reports", 14),
            entry("samhan-public", "회계", "미지급금 (거래처별)", "/accounting/reports/partner-aging?type=PAYABLE", "accounting.reports", 15),
            entry("samhan-public", "회계", "채권채무 현황", "/accounting/reports/receivables-payables", "accounting.reports", 16),
            entry("samhan-public", "회계", "받을어음", "/accounting/reports/notes-receivable", "accounting.reports", 17),
            entry("samhan-public", "회계", "수금계획", "/accounting/reports/collection-plans", "accounting.reports", 18),
            entry("samhan-public", "회계", "현금흐름표", "/accounting/reports/cash-flow", "accounting.reports", 19),
            entry("samhan-public", "회계", "자본변동표", "/accounting/reports/equity-changes", "accounting.reports", 20),
            entry("samhan-public", "회계", "일계표", "/accounting/reports/daily-summary", "accounting.reports", 21),
            entry("samhan-public", "회계", "월계표", "/accounting/reports/monthly-summary", "accounting.reports", 22),
            entry("samhan-public", "회계", "전표현황", "/accounting/reports/journal-status", "accounting.reports", 23),
            entry("samhan-public", "회계", "계정명세서", "/accounting/reports/account-statement", "accounting.reports", 24),
            entry("samhan-public", "회계", "자금현황", "/accounting/funds/status", "accounting.reports", 25),
            entry("samhan-public", "회계", "자금 입출금내역", "/accounting/reports/funds-flow-comparison", "accounting.reports", 26),
            entry("samhan-public", "회계", "매출 마감", "/sales/closing", "accounting.period-close", 27),
            entry("samhan-public", "회계", "월말 마감", "/accounting/period-close", "accounting.period-close", 28),
            entry("samhan-public", "회계", "영업수수료 정산", "/accounting/sales-commission-settlements", "accounting.sales-commission-settlement", 29),
            entry("samhan-public", "회계", "거래명세서 일괄", "/accounting/statement-batch", "accounting.statement-batch", 30),
            entry("samhan-public", "회계", "거래처 원장", "/accounting/partner-ledger", "accounting.partner-ledger", 31),
            entry("samhan-public", "회계", "홈택스 일괄 양식", "/accounting/hometax-export", "accounting.partner-ledger", 32),
            entry("samhan-public", "회계", "공급자 설정", "/accounting/supplier-profiles", "accounting.partner-ledger", 33),
            entry("samhan-public", "회계", "계좌/카드 관리", "/accounting/bank-card-admin", "accounting.bank-card-admin", 34),
            entry("samhan-public", "회계", "입출금 내역", "/accounting/bank-transactions", "accounting.bank-matching", 35),
            entry("samhan-public", "회계", "입금자명 매핑", "/accounting/deposit-mappings", "accounting.deposit-mapping", 36),
            entry("samhan-public", "회계", "입금보고서", "/accounting/admin/cash-receipts", "accounting.cash-receipts", 37),
            entry("samhan-public", "회계", "일마감", "/accounting/daily-closing", "accounting.daily-closing", 38),
            entry("samhan-public", "회계", "원장", "/accounting/ledgers", "accounting.general-ledger", 39),
            entry("samhan-public", "회계", "매출 원장 대조", "/accounting/admin/ledger/sales", "ecount.mig14.ledger", 40),
            entry("samhan-public", "회계", "매입 원장 대조", "/accounting/admin/ledger/purchase", "ecount.mig14.ledger", 41),
            entry("samhan-public", "회계", "운영 대시보드", "/accounting/admin/migration-ops", "ecount.mig.ops-dashboard", 42),
            entry("samhan-public", "회계", "회계 수정 요청", "/admin/accounting-edit-requests", "accounting.edit-requests.decide", 43),
            entry("samhan-public", "그룹웨어", "결재", "/groupware/approvals", "groupware.approvals", 1),
            entry("samhan-public", "그룹웨어", "결재 양식", "/groupware/approval-templates", "groupware.approval-templates", 2),
            entry("samhan-public", "그룹웨어", "결재 문서 양식", "/groupware/document-templates", "groupware.approval-templates", 3),
            entry("samhan-public", "그룹웨어", "링크발송", "/sales/link-dispatch", "slip.delivery-batch", 4),
            entry("samhan-public", "그룹웨어", "알리고 주소록", "/admin/aligo-address-book", "aligo.address-book", 5),
            entry("samhan-public", "그룹웨어", "메신저", "/messenger", "messenger.send", 6),
            entry("samhan-public", "그룹웨어", "단톡방 매핑", "/admin/chat-rooms", "messenger.admin", 7),
            entry("samhan-public", "인사", "인사 관리", "/admin/users", "admin.employees", 1),
            entry("samhan-public", "인사", "운송사 목록", "/admin/carriers", "hr.carriers", 2),
            entry("samhan-public", "인사", "결재라인 설정", "/admin/approval-line-config", "admin.approval-line-config", 3),
            entry("samhan-public", "인사", "출고 마감시간 설정", "/admin/slip-cutoff", "hr.slip-cutoff", 4),
            entry("samhan-public", "개발", "버전 관리", "/admin/app-releases", "admin.app-release", 1),
            entry("samhan-public", "배차", "배차현황", "/dispatch-board/history", "dispatch.board", 1),
            entry("samhan-public", "배차", "배차 그룹", "/admin/dispatch-groups", "dispatch.board", 2),
            entry("samhan-public", "배차", "가배차리스트", "/arologis/pre-classify", "arologis.dispatch.ops", 3),
            entry("samhan-public", "배차", "미배차리스트", "/arologis/unassigned", "arologis.dispatch.ops", 4),
            entry("samhan-public", "배차", "배차안내 SMS", "/arologis/dispatch-sms", "notification.dispatch-sms.display", 5),
            entry("samhan-public", "배차", "실배차 비교", "/arologis/dispatch-reconcile", "arologis.dispatch.ops", 6),
            entry("samhan-public", "배차", "배차지역 관리", "/admin/regions", "arologis.region", 7),
            entry("samhan-public", "배차", "외부기사/배송사", "/admin/external-carriers", "dispatch.external-carriers", 8),
            entry("samhan-public", "배차", "자동 매칭", "/arologis/admin/auto-dispatch", "arologis.admin", 9),
            entry("samhan-public", "배차", "배차 관리", "/arologis/admin/manual-dispatch", "arologis.admin", 10),
            entry("samhan-public", "배차", "기사 배정", "/arologis/admin/driver-assignment", "arologis.admin", 11),
            entry("samhan-public", "창고 운영", "창고관리", "/warehouses", "inventory.warehouse", 1),
            entry("samhan-public", "창고 운영", "재고 현황", "/inventory/stock-balance", "inventory.stock-balance", 2),
            entry("samhan-public", "창고 운영", "입출고 내역·분석", "/inventory/inout-analysis", "accounting.sales-slip.list", 3),
            entry("samhan-public", "창고 운영", "안전재고 알림", "/inventory/safety-stock-alerts", "inventory.safety-stock", 4),
            entry("samhan-public", "창고 운영", "보상 실패 복구", "/inventory/compensation-failures", "inventory.list", 5),
            entry("samhan-public", "창고 운영", "전표 수정 요청", "/admin/slip-edit-requests", "slip.edit-requests.decide", 6),
            entry("samhan-public", "창고 운영", "사진 감사", "/admin/photo-audit", "slip.photo-audit", 7),
            entry("arologis", "배차", "수동 배차", "/dispatches/manual", "arologis.dispatch.admin", 1),
            entry("arologis", "배차", "가배차 분류", "/dispatches/pre-classify", "arologis.dispatch.ops", 2),
            entry("arologis", "배차", "미배차", "/dispatches/unassigned", "arologis.dispatch.ops", 3),
            entry("arologis", "배차", "실배차 비교", "/dispatches/reconcile", "arologis.dispatch.ops", 4),
            entry("arologis", "배차", "수신 배차 그룹", "/dispatches/received-groups", "arologis.dispatch.ops", 5));

    private MenuCatalog() {
    }

    public static List<MenuCatalogEntry> entries() {
        return ENTRIES;
    }

    private static MenuCatalogEntry entry(String app, String category, String label, String route,
                                          String pageCode, int order) {
        return new MenuCatalogEntry(app, category, label, route, pageCode, "VIEW", true, order);
    }
}
