-- V32__add_staff_driver_matrix_rows.sql
-- SP-D6-2 cycle 1f: STAFF/DRIVER role 을 권한 매트릭스 기본 행에 통합.
-- 명시 권한이 생기기 전까지 모든 PageCode 는 보수적 FALSE/FALSE 로 시작한다.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO role_page_permissions
    (id, role_code, page_code, can_view, can_edit, created_at, created_by, is_deleted)
SELECT gen_random_uuid(), r.role_code, p.page_code, FALSE, FALSE, NOW(), 'system', FALSE
FROM (VALUES
    ('STAFF'),
    ('DRIVER')
) AS r(role_code)
CROSS JOIN (VALUES
    ('accounting.accounts'),
    ('accounting.balances'),
    ('accounting.daily-closing'),
    ('accounting.deposit-match'),
    ('accounting.edit-requests'),
    ('accounting.general-ledger'),
    ('accounting.journals'),
    ('accounting.partner-ledger'),
    ('accounting.period-close'),
    ('accounting.purchase-slip.list'),
    ('accounting.reports'),
    ('accounting.sales-slip.list'),
    ('accounting.statement-batch'),
    ('accounting.tax-invoice.batch-issue'),
    ('accounting.tax-invoice.emit-nts'),
    ('accounting.tax-invoice.inbound'),
    ('accounting.tax-invoice.list'),
    ('admin.employees'),
    ('admin.permissions'),
    ('admin.users'),
    ('arologis.admin'),
    ('arologis.region'),
    ('dashboard.admin'),
    ('dc-config.import'),
    ('dispatch.board'),
    ('ecount.mig.ops-dashboard'),
    ('ecount.mig10.order-employee-backfill'),
    ('ecount.mig11.purchase-ledger'),
    ('ecount.mig11.sales-ledger'),
    ('ecount.mig14.aging-snapshot'),
    ('ecount.mig14.cash-list'),
    ('ecount.mig14.ledger'),
    ('ecount.mig14.order-list'),
    ('ecount.mig2.account'),
    ('ecount.mig2.card'),
    ('ecount.mig2.department'),
    ('ecount.mig2.product'),
    ('ecount.mig2.warehouse'),
    ('ecount.mig3.general-voucher'),
    ('ecount.mig3.journal-entry'),
    ('ecount.mig3.purchase-slip'),
    ('ecount.mig3.sales-slip'),
    ('ecount.mig4.order'),
    ('ecount.mig4.sales-slip-line'),
    ('ecount.mig4.summary'),
    ('ecount.mig4.tax-invoice'),
    ('ecount.mig5.deposit-report'),
    ('ecount.mig5.expense-voucher'),
    ('ecount.mig5.stock-transfer'),
    ('ecount.mig6.bank-account'),
    ('ecount.mig6.employee'),
    ('ecount.mig6.employee-card'),
    ('ecount.mig6.fixed-asset-type'),
    ('ecount.mig6.payroll-employee'),
    ('ecount.mig7.cash-disbursement'),
    ('ecount.mig7.cash-receipt'),
    ('ecount.mig8.order'),
    ('ecount.mig9.cash-journal.disbursement'),
    ('ecount.mig9.cash-journal.receipt'),
    ('ecount.reimport'),
    ('estimates.list'),
    ('inbound.inspection'),
    ('inventory.audit'),
    ('inventory.dps'),
    ('inventory.stock'),
    ('inventory.stock-transfer'),
    ('inventory.warehouse'),
    ('messenger.admin'),
    ('messenger.send'),
    ('notification.dispatch-sms.send-audit'),
    ('partners.block'),
    ('partners.detail'),
    ('partners.edit-request'),
    ('partners.list'),
    ('products.admin'),
    ('products.ecount-import'),
    ('products.edit-requests'),
    ('products.edit-requests.decide'),
    ('products.list'),
    ('products.price'),
    ('purchases.receipt-ocr'),
    ('purchases.slip.list'),
    ('sales.partner-dc-config'),
    ('sales.partner-order.confirm'),
    ('sales.partner-order.draft'),
    ('sales.partner-order.edit'),
    ('sales.partner-order.edit-requests'),
    ('sales.partner-order.edit-requests.decide'),
    ('sales.partner-order.history'),
    ('sales.partner-order.list'),
    ('sales.partner-order.print'),
    ('sales.partner-order.tutorial'),
    ('sales.slip.list'),
    ('sales.vendor-order'),
    ('system.account-admin'),
    ('system.password-admin'),
    ('system.permission-admin')
) AS p(page_code)
ON CONFLICT DO NOTHING;
